"""Add image upload functionality

Revision ID: 167291ab3671
Revises: eb3fcde40f6d
Create Date: 2024-07-26 09:53:29.269489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167291ab3671'
down_revision = 'eb3fcde40f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('filename',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=256),
               nullable=False)
        batch_op.drop_column('data')
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('data', sa.BLOB(), nullable=True))
        batch_op.alter_column('filename',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=140),
               nullable=True)
        batch_op.drop_column('upload_date')

    op.create_table('task',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=140), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
